import type { Metadata } from "next";
import { Merienda, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merienda.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex=col relative flex h-full w-full items-center justify-items-center bg-bgp font-sans text-white">
          <main className="flex h-full w-full flex-col items-center justify-center border-4 border-yellow-400">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}